stages:
  - build
  - deploy

build_site:
  image: python:3.6-alpine
  stage: build
  script:
    - pip install -r requirements.txt
    - cd mkdocs_jinja_plugin
    - pip install .
    - cd ..
    - mkdocs build
  artifacts:
    paths:
      - site
  
push_site:
  stage: deploy
  script:
    - unset PYTHONHOME
    - echo "$ATSJENKINS_PASSWORD" | kinit atsjenkins@CERN.CH 2>&1 >/dev/null
    - ./deploy_website
    environment:
      name: prod
      url: https://acts.web.cern.ch/ACTS/
  only:
    - master
