#!/usr/bin/env bash

function krb5logout {
  echo "* Destroying Kerberos 5 ticket..."
    kdestroy
}

# always log out when script is exited
trap krb5logout EXIT

# abort on error
set -ex

# configure ssh to use kerberos
mkdir -p ~/.ssh/
echo "GSSAPIAuthentication yes
GSSAPITrustDNS yes
StrictHostKeyChecking no
GSSAPIDelegateCredentials yes" > ~/.ssh/config

rsync -ruv site/ atsjenkins@lxplus.cern.ch:~/www --exclude="*.j2"
