site_name: ACTS

theme:
  name: mkdocs
  custom_dir: mkdocs_acts

extra:
  links:
    - title: Doxygen
      url: http://acts.web.cern.ch/ACTS/latest/doc/index.html
      target: _blank

markdown_extensions:
  - pymdownx.arithmatex:
      generic: yes

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/contrib/auto-render.min.js
  - katex-enable.js

pages:
    - Home: index.md
    - Releases: releases.md
    - Modules :
        - Geometry : modules_geometry.md
        - Event Data : modules_eventdata.md
        - Propagation : modules_propagation.md 
        - Pattern Recognition: modules_pattern.md
        - Track fitting: modules_fitting.md
    - Guides :
        - Users Guide : guides_users.md
        - Developers Guide : guides_developers.md
        - Contribution Guide : guides_contribution.md
        - CI and Testing Guide : guides_testing.md
        - Administrators Guide: guides_admin.md
    - Clients:
        - Integration: integration.md
        - Integration in ATLAS: integration_atlas.md
        - Integration in FCCSW: integration_fcc.md
        - Tracking Machine Learning Challenge: integration_trackml.md