site_name: ACTS

theme:
  name: mkdocs
  custom_dir: mkdocs_acts

plugins:
  - search
  - jinja:
      gitlab_url: https://gitlab.cern.ch/api/v4/
      repo: acts/acts-core
      contributor_email_map: 
        knights_of_ni@gmx.com: "grasland@lal.in2p3.fr"
        hello@paulgessinger.com: "paul.gessinger@cern.ch"
        rlangenb@cern.ch: "robert.langenberg@cern.ch"
        Andreas.Salzburger@cern.ch: "andreas.salzburger@cern.ch"
        cgumpert@cern.ch: "christian.gumpert@cern.ch"
      contributor_name_map:
        "julia.hrdinka@cern.ch": "Julia Hrdinka"
      contributor_exclude:
        - ats.jenkins@cern.ch
      url_imports:
        license: https://gitlab.cern.ch/acts/acts-core/raw/master/LICENSE
        readme: https://gitlab.cern.ch/acts/acts-core/raw/master/README.md
        contributing: https://gitlab.cern.ch/acts/acts-core/raw/master/CONTRIBUTING.md


extra:
  links:
    - title: Doxygen
      url: http://acts.web.cern.ch/ACTS/latest/doc/index.html
      target: _blank

markdown_extensions:
  - pymdownx.arithmatex:
      generic: yes

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/contrib/auto-render.min.js
  - katex-enable.js

pages:
    - Home: index.md
    - About:
        - Authors: authors.md
        - License: license.md
    - Releases: releases.md
    - Modules :
        - Geometry : modules_geometry.md
        - Event Data : modules_eventdata.md
        - Propagation : modules_propagation.md 
        - Pattern Recognition: modules_pattern.md
        - Track fitting: modules_fitting.md
    - Guides :
        - Users Guide : guides_users.md
        - Developers Guide : guides_developers.md
        - Contribution Guide : guides_contribution.md
        - CI and Testing Guide : guides_testing.md
        - Administrators Guide: guides_admin.md
    - Clients:
        - Integration: integration.md
        - Integration in ATLAS: integration_atlas.md
        - Integration in FCCSW: integration_fcc.md
        - Tracking Machine Learning Challenge: integration_trackml.md
