site_name: Acts

theme:
  name: mkdocs
  custom_dir: mkdocs_acts

repo_url: https://gitlab.cern.ch/acts/acts-core
repo_name: GitLab

plugins:
  - search
  - jinja:
      gitlab_url: https://gitlab.cern.ch
      repo: acts/acts-core
      url_imports:
        license: https://gitlab.cern.ch/acts/acts-core/raw/master/LICENSE
        readme: https://gitlab.cern.ch/acts/acts-core/raw/master/README.md
        getting_started: https://gitlab.cern.ch/acts/acts-core/raw/master/getting_started.md
        contributing: https://gitlab.cern.ch/acts/acts-core/raw/master/CONTRIBUTING.md
        authors: https://gitlab.cern.ch/acts/acts-core/raw/master/AUTHORS.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: yes
  - toc:
  - admonition: {}

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/contrib/auto-render.min.js
  - katex-enable.js

nav:
    - Home: index.md
    - About:
      - Authors: authors.md
      - License: license.md
      - Documentation: http://acts.web.cern.ch/ACTS/latest/doc/index.html
    - Modules :
        - Geometry : modules_geometry.md
        - Event Data : modules_eventdata.md
        - Propagation : modules_propagation.md 
        - Pattern Recognition: modules_pattern.md
        - Track fitting: modules_fitting.md
    - Guides :
        - Users Guide : guides_users.md
        - Developers Guide : guides_developers.md
        - Contribution Guide : guides_contribution.md
        - Framework Examples Guide : guides_framework.md
        - CI and Testing Guide : guides_testing.md
        - Administrators Guide: guides_admin.md
    - Clients:
        - Integration: integration.md
        - Integration in ATLAS: integration_atlas.md
        - Integration in FCCSW: integration_fcc.md
        - Tracking Machine Learning Challenge: integration_trackml.md
