var searchData=
[
  ['a_20backend_0',['How to build a backend',['../group__eventdata__tracks.html#autotoc_md21',1,'']]],
  ['a_20container_1',['In a container',['../building_acts.html#autotoc_md3',1,'']]],
  ['a_20cpu_20profile_2',['Produce a CPU Profile',['../howto_profiling.html#autotoc_md44',1,'']]],
  ['a_20graph_3',['View Profile as a Graph',['../howto_profiling.html#autotoc_md48',1,'']]],
  ['a_20lcg_20release_20on_20cvmfs_4',['With a LCG release on CVMFS',['../building_acts.html#autotoc_md2',1,'']]],
  ['a_20memory_20profile_5',['Produce a Memory Profile',['../howto_profiling.html#autotoc_md45',1,'']]],
  ['a_20nutshell_6',['Tracking in a nutshell',['../tracking.html',1,'']]],
  ['a_20physmon_20failure_7',['How do I investigate a physmon failure?',['../physmon.html#autotoc_md36',1,'']]],
  ['a_20release_8',['How to make a release',['../howto_release.html',1,'']]],
  ['a_20track_20from_20scratch_9',['How to create a track from scratch',['../group__eventdata__tracks.html#autotoc_md17',1,'']]],
  ['accessors_10',['Accessors',['../group__eventdata__tracks.html#edm_track_accessors',1,'']]],
  ['acts_11',['ACTS',['../group__eventdata__tracks.html#autotoc_md18',1,'Backends shipped with ACTS'],['../building_acts.html',1,'Building ACTS'],['../building_acts.html#building-acts',1,'Building ACTS'],['../group__errors.html#autotoc_md8',1,'Error Handling in ACTS']]],
  ['acts_20in_20downstream_20code_12',['Using ACTS in downstream code',['../building_acts.html#autotoc_md7',1,'']]],
  ['advanced_20topics_13',['Advanced Topics',['../group__logging.html#autotoc_md30',1,'']]],
  ['alternative_20to_20recompiling_14',['Alternative to Recompiling',['../howto_profiling.html#autotoc_md43',1,'']]],
  ['ambiguity_20resolution_15',['Ambiguity resolution',['../tracking.html#ambiguity-resolution',1,'']]],
  ['and_20forward_20linking_16',['Track state iteration and forward linking',['../group__eventdata__tracks.html#edm_track_iteration',1,'']]],
  ['and_20how_20to_20update_20the_20reference_20hashes_17',['and how to update the reference hashes',['../md_docs_2pages_2examples_2python__bindings.html#autotoc_md65',1,'Running the hash checks locally and how to update the reference hashes'],['../python_bindings.html#autotoc_md70',1,'Running the hash checks locally and how to update the reference hashes']]],
  ['and_20kalman_20track_20fitter_18',['Kalman formalism and Kalman track fitter',['../tracking.html#kalman-formalism',1,'']]],
  ['and_20material_20modelling_19',['Geometry and material modelling',['../tracking.html#geometry-and-material-modelling',1,'']]],
  ['and_20public_20api_20',['Versioning and public API',['../versioning.html',1,'']]],
  ['and_20sourcelinks_21',['Helper for &lt;span class=&quot;tt&quot;&gt;Surface&lt;/span&gt;s and &lt;span class=&quot;tt&quot;&gt;SourceLink&lt;/span&gt;s',['../group__eventdata__tracks.html#podio_helper',1,'']]],
  ['and_20track_20fitting_22',['Track finding and track fitting',['../tracking.html#track-finding-and-track-fitting',1,'']]],
  ['api_23',['API',['../versioning.html#autotoc_md67',1,'Private API'],['../versioning.html#autotoc_md66',1,'Public API'],['../versioning.html',1,'Versioning and public API']]],
  ['architecture_24',['Architecture',['../group__eventdata__tracks.html#autotoc_md14',1,'']]],
  ['argument_20pattern_25',['Const Reference Argument Pattern',['../group__logging.html#autotoc_md27',1,'']]],
  ['as_20a_20graph_26',['View Profile as a Graph',['../howto_profiling.html#autotoc_md48',1,'']]]
];
